export {default as Blog} from './blog/blog'
export {default as Footer} from './footer/footer'
export {default as Header} from './header/header'
export {default as Features} from './features/features'
export {default as Whatgpt3} from './whatgpt3/whatgpt3'
export {default as Possibility} from './possibility/possibility'